version: '2'
services:
  db:
    image: postgres:9.4
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=shipup_test
      - POSTGRES_USER=postgres
      - PGPORT=5432

  spec:
    build: .
    volumes:
      - './spec:/shipup_test/spec'
      - './.rspec:/shipup_test/.rspec'
      - './glexport_development.psql.dump:/shipup_test/glexport_development.psql.dump'
      - './glexport_development.mysql.dump:/shipup_test/glexport_development.mysql.dump'
    links:
      - db
    environment:
      - PGHOST=db
      - PGPORT=5432
      - PGUSER=postgres
      - PGDATABASE=shipup_test
      - WAIT_HOSTS=db:5432
      # - MYSQL_HOST=db
      # - MYSQL_PWD=db_password
      # - WAIT_HOSTS=db:3306

